language: rust
rust:
  - nightly
  - stable
os:
  - linux
cache:
  cargo: true
  apt: true
addons:
  apt:
    packages:
      - libsodium-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - zlib1g-dev

    sources:
      - sourceline: ppa:chris-lea/libsodium
      - kalakris-cmake
# Add clippy
before_script:
  - cargo install --force cargo-travis
script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" && $CLIPPY ]]; then
        cargo clippy
      fi
  - |
      cargo build &&
      cargo test
after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    cargo coveralls --exclude-pattern tests/;
  fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/047c31225e476090980a
    on_success: always
    on_failure: always
    on_start: never